name: Build and Push to DOCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DOCR
        run: doctl registry login --expiry-seconds 300

      - name: Build image
        run: docker build -t registry.digitalocean.com/tasky-registry/tasky:latest .

      - name: Push image
        run: docker push registry.digitalocean.com/tasky-registry/tasky:latest
