name: Build and Push to DOCR

on:
  push:
    branches:
      - main

env:
  REGISTRY_NAME: "tasky-registry" # Replace with your DOCR name
  IMAGE_NAME: "tasky"         # Replace with your image name

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 1200

      - name: Build Docker image
        run: docker build -t ://digitalocean.com{{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Push image to DOCR
        run: docker build -t ://digitalocean.com{{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:latest . && docker push --all-tags ://digitalocean.com{{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}
